service: github-notifications-slack

custom:
  defaultStage: dev

provider:
  name: aws
  runtime: provided
  timeout: 300
  region: ap-northeast-1
  ecr:
    images:
      appImage:
        path: ./
        platform: linux/amd64
  stage: ${opt:stage, self:custom.defaultStage}
  environment:
    ${file(./env.yml)}

functions:
  github_notifications_slack:
    image:
      name: appImage
      command:
        - github_notifications_slack
    events:
      - schedule: rate(1 minute)
